
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action NuevoAction;
	private global::Gtk.Action AbrirAction;
	private global::Gtk.Action ArchivoAction;
	private global::Gtk.Action EditarAction;
	private global::Gtk.Action FormatoAction;
	private global::Gtk.Action SalirAction;
	private global::Gtk.Action newAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action newAction1;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction1;
	private global::Gtk.Action saveAsAction;
	private global::Gtk.Action cutAction;
	private global::Gtk.Action copyAction;
	private global::Gtk.Action pasteAction;
	private global::Gtk.Action boldAction;
	private global::Gtk.Action italicAction;
	private global::Gtk.Action underlineAction;
	private global::Gtk.Action selectFontAction;
	private global::Gtk.Action ArialAction;
	private global::Gtk.Action ComicSansAction;
	private global::Gtk.Action quitAction1;
	private global::Gtk.Action quitAction2;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView campoTexto;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.NuevoAction = new global::Gtk.Action ("NuevoAction", global::Mono.Unix.Catalog.GetString ("Nuevo"), null, null);
		this.NuevoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nuevo");
		w1.Add (this.NuevoAction, null);
		this.AbrirAction = new global::Gtk.Action ("AbrirAction", global::Mono.Unix.Catalog.GetString ("Abrir"), null, null);
		this.AbrirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Abrir");
		w1.Add (this.AbrirAction, null);
		this.ArchivoAction = new global::Gtk.Action ("ArchivoAction", global::Mono.Unix.Catalog.GetString ("Archivo"), null, null);
		this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Archivo");
		w1.Add (this.ArchivoAction, null);
		this.EditarAction = new global::Gtk.Action ("EditarAction", global::Mono.Unix.Catalog.GetString ("Editar"), null, null);
		this.EditarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar");
		w1.Add (this.EditarAction, null);
		this.FormatoAction = new global::Gtk.Action ("FormatoAction", global::Mono.Unix.Catalog.GetString ("Formato"), null, null);
		this.FormatoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Formato");
		w1.Add (this.FormatoAction, null);
		this.SalirAction = new global::Gtk.Action ("SalirAction", global::Mono.Unix.Catalog.GetString ("Salir"), null, null);
		this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Salir");
		w1.Add (this.SalirAction, null);
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", null, null, "gtk-quit");
		w1.Add (this.quitAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", global::Mono.Unix.Catalog.GetString ("_Nuevo"), null, "gtk-new");
		this.newAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Nuevo");
		w1.Add (this.newAction1, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("_Abrir"), null, "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Abrir");
		w1.Add (this.openAction1, null);
		this.saveAction1 = new global::Gtk.Action ("saveAction1", global::Mono.Unix.Catalog.GetString ("_Guardar"), null, "gtk-save");
		this.saveAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Guardar");
		w1.Add (this.saveAction1, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Guardar co_mo"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Guardar co_mo");
		w1.Add (this.saveAsAction, null);
		this.cutAction = new global::Gtk.Action ("cutAction", global::Mono.Unix.Catalog.GetString ("Cor_tar"), null, "gtk-cut");
		this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cor_tar");
		w1.Add (this.cutAction, null);
		this.copyAction = new global::Gtk.Action ("copyAction", global::Mono.Unix.Catalog.GetString ("_Copiar"), null, "gtk-copy");
		this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Copiar");
		w1.Add (this.copyAction, null);
		this.pasteAction = new global::Gtk.Action ("pasteAction", global::Mono.Unix.Catalog.GetString ("_Pegar"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Pegar");
		w1.Add (this.pasteAction, null);
		this.boldAction = new global::Gtk.Action ("boldAction", global::Mono.Unix.Catalog.GetString ("_Negrita"), null, "gtk-bold");
		this.boldAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Negrita");
		w1.Add (this.boldAction, null);
		this.italicAction = new global::Gtk.Action ("italicAction", global::Mono.Unix.Catalog.GetString ("_Cursiva"), null, "gtk-italic");
		this.italicAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Cursiva");
		w1.Add (this.italicAction, null);
		this.underlineAction = new global::Gtk.Action ("underlineAction", global::Mono.Unix.Catalog.GetString ("_Subrayar"), null, "gtk-underline");
		this.underlineAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Subrayar");
		w1.Add (this.underlineAction, null);
		this.selectFontAction = new global::Gtk.Action ("selectFontAction", global::Mono.Unix.Catalog.GetString ("_Tipografía"), null, "gtk-select-font");
		this.selectFontAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Tipografía");
		w1.Add (this.selectFontAction, null);
		this.ArialAction = new global::Gtk.Action ("ArialAction", global::Mono.Unix.Catalog.GetString ("Arial"), null, null);
		this.ArialAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Arial");
		w1.Add (this.ArialAction, null);
		this.ComicSansAction = new global::Gtk.Action ("ComicSansAction", global::Mono.Unix.Catalog.GetString ("Comic Sans"), null, null);
		this.ComicSansAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Comic Sans");
		w1.Add (this.ComicSansAction, null);
		this.quitAction1 = new global::Gtk.Action ("quitAction1", global::Mono.Unix.Catalog.GetString ("_Salir"), null, "gtk-quit");
		this.quitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Salir");
		w1.Add (this.quitAction1, null);
		this.quitAction2 = new global::Gtk.Action ("quitAction2", global::Mono.Unix.Catalog.GetString ("_Salir"), null, "gtk-quit");
		this.quitAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Salir");
		w1.Add (this.quitAction2, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Editor de textos");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='newAction1' action='newAction1'/><menuitem name='openAction1' action='openAction1'/><menuitem name='saveAction1' action='saveAction1'/><menuitem name='saveAsAction' action='saveAsAction'/><menuitem name='quitAction2' action='quitAction2'/></menu><menu name='EditarAction' action='EditarAction'><menuitem name='cutAction' action='cutAction'/><menuitem name='copyAction' action='copyAction'/><menuitem name='pasteAction' action='pasteAction'/></menu><menu name='FormatoAction' action='FormatoAction'><menuitem name='boldAction' action='boldAction'/><menuitem name='italicAction' action='italicAction'/><menuitem name='underlineAction' action='underlineAction'/><menu name='selectFontAction' action='selectFontAction'><menuitem name='ArialAction' action='ArialAction'/><menuitem name='ComicSansAction' action='ComicSansAction'/></menu></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='quitAction' action='quitAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
		this.toolbar1.IconSize = ((global::Gtk.IconSize)(1));
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.campoTexto = new global::Gtk.TextView ();
		this.campoTexto.CanFocus = true;
		this.campoTexto.Name = "campoTexto";
		this.GtkScrolledWindow.Add (this.campoTexto);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w5.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 569;
		this.DefaultHeight = 464;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.newAction1.Activated += new global::System.EventHandler (this.OnNewAction1Activated);
		this.openAction1.Activated += new global::System.EventHandler (this.OnOpenAction1Activated);
	}
}
